# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Mats Nils Karlsson
# Glimra — MQTT LED Matrix Display Firmware
# https://github.com/mats-nk/Glimra

"""
compress_html.py  —  PlatformIO extra_scripts build step
=========================================================
Runs before compilation. Reads  web/index.html,
gzip-compresses it at level 9, and writes the result as
a C byte-array into include/html_page.h.

The generated header defines:
    extern const uint8_t  HTML_GZ[];       // gzip data in PROGMEM
    extern const uint32_t HTML_GZ_LEN;     // byte count

webserver.h serves this with:
    server.sendHeader("Content-Encoding", "gzip");
    server.send_P(200, "text/html", (const char*)HTML_GZ, HTML_GZ_LEN);

Adding this file to platformio.ini:
    extra_scripts = pre:compress_html.py
"""

import gzip, os, re
from datetime import datetime, timezone

Import("env")   # noqa: F821  — PlatformIO SCons environment


def compress_html(source, target, env):
    project_dir = env.subst("$PROJECT_DIR")
    src  = os.path.join(project_dir, "web",     "index.html")
    dst  = os.path.join(project_dir, "include", "html_page.h")

    if not os.path.isfile(src):
        print(f"[compress_html] ERROR: {src} not found — skipping")
        return

    with open(src, "rb") as f:
        raw = f.read()

    compressed = gzip.compress(raw, compresslevel=9)

    ratio   = len(compressed) / len(raw) * 100
    saved   = len(raw) - len(compressed)
    ts      = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Format as a C byte array — 12 bytes per line, always keeping 0x prefix intact
    byte_strs  = [f"0x{b:02X}" for b in compressed]
    rows       = [byte_strs[i:i+12] for i in range(0, len(byte_strs), 12)]
    hex_block  = "\n    ".join(", ".join(row) + "," for row in rows).rstrip(",")

    header = f"""\
// html_page.h — AUTO-GENERATED by compress_html.py — DO NOT EDIT
// Source  : web/index.html  ({len(raw)} bytes)
// Gzipped : {len(compressed)} bytes  ({ratio:.1f}% of original, {saved} bytes saved)
// Built   : {ts}
//
// Served with:
//   server.sendHeader("Content-Encoding", "gzip");
//   server.send_P(200, "text/html", (const char*)HTML_GZ, HTML_GZ_LEN);

#pragma once
#include <Arduino.h>

static const uint32_t HTML_GZ_LEN = {len(compressed)}UL;

static const uint8_t HTML_GZ[] PROGMEM = {{
    {hex_block}
}};
"""

    # Only write if content actually changed (avoids unnecessary recompilation)
    existing = ""
    if os.path.isfile(dst):
        with open(dst) as f:
            existing = f.read()

    # Strip the timestamp line before comparing so a same-HTML rebuild
    # doesn't force recompilation just because the time changed.
    def strip_ts(text):
        return re.sub(r"// Built\s+:.*", "", text)

    if strip_ts(header) != strip_ts(existing):
        with open(dst, "w") as f:
            f.write(header)
        print(f"[compress_html] {len(raw)}B -> {len(compressed)}B "
              f"({ratio:.1f}%) -> include/html_page.h")
    else:
        print("[compress_html] html_page.h is up to date — skipping")


env.AddPreAction("buildprog", compress_html)
