// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Mats Nils Karlsson
// Glimra — MQTT LED Matrix Display Firmware
// https://github.com/mats-nk/Glimra

#pragma once
// webserver.h - Web server + REST API for MQTT Matrix Display

#ifdef ESP8266
  #include <ESP8266WebServer.h>
  using WebSrv = ESP8266WebServer;
#else
  #include <WebServer.h>
  using WebSrv = WebServer;
#endif

#include "config_io.h"  // AppConfig + JSON helpers + defaults
#include "storage.h"

// Forward declarations (defined in main.cpp)
extern AppConfig gCfg;
extern void onConfigSaved();
extern void onIntensityChange(uint8_t val);
extern void doWifiReset();

// DisplayManager forward (full type in display.h, included in main.cpp)
class DisplayManager;
extern DisplayManager gDisplay;

// ------------------------------------------------------------------
// Minimal embedded HTML — full SPA served from PROGMEM
// ------------------------------------------------------------------
#include "html_page.h"   // AUTO-GENERATED: defines HTML_GZ[] + HTML_GZ_LEN (PROGMEM gzip)

// ------------------------------------------------------------------
class WebUI {
public:
    WebUI() : _srv(80) {}

    void begin() {
        _srv.on("/",             HTTP_GET,  [this](){ _root(); });
        _srv.on("/api/config",   HTTP_GET,  [this](){ _getCfg(); });
        _srv.on("/api/config",   HTTP_POST, [this](){ _setCfg(); });
        _srv.on("/api/status",   HTTP_GET,  [this](){ _status(); });
        _srv.on("/api/message",  HTTP_POST, [this](){ _message(); });
        _srv.on("/api/intensity",HTTP_POST, [this](){ _intensity(); });
        _srv.on("/api/resetwifi",HTTP_POST, [this](){ _resetWifi(); });
        _srv.on("/api/factory",  HTTP_POST, [this](){ _factory(); });
        _srv.onNotFound([this](){ _srv.send(404,"text/plain","404"); });
        _srv.begin();
        Serial.println("[WEB] HTTP server on port 80");
    }

    void handle() { _srv.handleClient(); }

    // Public state written by main loop
    bool   mqttOk  = false;
    char   lastMsg[256] = "";
    char   ipStr[20]    = "0.0.0.0";
    int8_t rssiVal      = 0;

private:
    WebSrv _srv;

    void _cors() { _srv.sendHeader("Access-Control-Allow-Origin","*"); }

    void _root() {
        // html_page.h is auto-generated by compress_html.py (pre-build script).
        // It defines HTML_GZ[] (PROGMEM) and HTML_GZ_LEN.
        // The browser decompresses gzip transparently.
        _srv.sendHeader("Content-Encoding", "gzip");
        _srv.sendHeader("Cache-Control", "no-cache");
        _srv.send_P(200, "text/html",
                    reinterpret_cast<const char*>(HTML_GZ),
                    HTML_GZ_LEN);
    }

    void _getCfg() {
        JsonDocument doc; configToJson(gCfg, doc);
        String s; serializeJson(doc, s);
        _cors(); _srv.send(200,"application/json",s);
    }

    void _setCfg() {
        if (!_srv.hasArg("plain")){ _srv.send(400,"text/plain","no body"); return; }
        JsonDocument doc;
        if (deserializeJson(doc, _srv.arg("plain"))){
            _srv.send(400,"text/plain","bad json"); return;
        }
        jsonToConfig(doc, gCfg);
        Storage::saveConfig(gCfg);
        _cors(); _srv.send(200,"application/json","{\"ok\":true}");
        onConfigSaved();
    }

    void _status() {
        // lastMsg is stored as Latin-1 after UTF-8→Latin-1 conversion.
        // Convert it back to UTF-8 before embedding in JSON so the browser
        // renders accented characters correctly (å ä ö etc.).
        char utf8Msg[512];
        _latin1ToUtf8(lastMsg, utf8Msg, sizeof(utf8Msg));

        JsonDocument doc;
        doc["mqtt_connected"] = mqttOk;
        doc["last_msg"]       = utf8Msg;
        doc["ip"]             = ipStr;
        doc["rssi"]           = rssiVal;
        doc["uptime"]         = (uint32_t)(millis()/1000);
        doc["heap"]           = (uint32_t)ESP.getFreeHeap();
        doc["version"]        = FIRMWARE_VERSION;
#ifdef ESP8266
        doc["board"]   = "ESP8266";
        doc["chip_id"] = String(ESP.getChipId(), HEX);
#else
        doc["board"]   = "ESP32-S2";
        doc["chip_id"] = String((uint32_t)ESP.getEfuseMac(), HEX);
#endif
        String s; serializeJson(doc, s);
        _cors(); _srv.send(200,"application/json",s);
    }

    void _message() {
        if (!_srv.hasArg("plain")){ _srv.send(400,"text/plain",""); return; }
        JsonDocument doc; deserializeJson(doc, _srv.arg("plain"));
        const char* m = doc["msg"] | "";
        char buf[256];
        strncpy(buf, m, sizeof(buf)-1);
        buf[sizeof(buf)-1] = '\0';
        _utf8ToLatin1(buf);
        strncpy(lastMsg, buf, sizeof(lastMsg)-1);
        gDisplay.showMessage(buf);
        // Check immediately after queuing — isLongMessage gives the same
        // answer as the auto-scroll check inside display.h
        bool longMsg = gDisplay.isLongMessage(buf);
        bool willScroll = longMsg && (gCfg.anim_in != 4 && gCfg.anim_in != 5
                                   && gCfg.anim_out != 4 && gCfg.anim_out != 5);
        if (willScroll)
            _cors(), _srv.send(200,"application/json","{\"ok\":true,\"auto_scrolled\":true}");
        else
            _cors(), _srv.send(200,"application/json","{\"ok\":true,\"auto_scrolled\":false}");
    }

    // UTF-8 → Latin-1 in-place (mirrors MqttManager::_utf8ToLatin1)
    static void _utf8ToLatin1(char* s) {
        uint8_t* r = (uint8_t*)s;
        uint8_t* w = (uint8_t*)s;
        while (*r) {
            if (*r < 0x80)                                           { *w++=*r++; }
            else if (*r==0xC2 && *(r+1)>=0x80 && *(r+1)<=0xBF)     { *w++=*(r+1); r+=2; }
            else if (*r==0xC3 && *(r+1)>=0x80 && *(r+1)<=0xBF)     { *w++=(uint8_t)(*(r+1)+0x40); r+=2; }
            else if (*r>=0xC4 && *r<=0xDF)                          { *w++='?'; r+=2; }
            else if (*r>=0xE0 && *r<=0xEF)                          { *w++='?'; r+=3; }
            else if (*r>=0xF0)                                       { *w++='?'; r+=4; }
            else                                                     { r++; }
        }
        *w='\0';
    }

    // Latin-1 → UTF-8 for JSON responses sent to the browser.
    // Latin-1 bytes 0x00–0x7F are unchanged (valid ASCII/UTF-8).
    // Bytes 0x80–0xFF expand to two-byte UTF-8 sequences:
    //   0x80–0xBF  →  0xC2 + byte
    //   0xC0–0xFF  →  0xC3 + (byte - 0x40)
    static void _latin1ToUtf8(const char* src, char* dst, size_t dstLen) {
        const uint8_t* r = (const uint8_t*)src;
        uint8_t*       w = (uint8_t*)dst;
        uint8_t* end     = w + dstLen - 1;   // reserve space for null terminator
        while (*r && w < end) {
            if (*r < 0x80) {
                *w++ = *r++;
            } else if (*r < 0xC0) {
                // 0x80–0xBF: encode as 0xC2 + byte
                if (w + 1 >= end) break;
                *w++ = 0xC2;
                *w++ = *r++;
            } else {
                // 0xC0–0xFF: encode as 0xC3 + (byte - 0x40)
                if (w + 1 >= end) break;
                *w++ = 0xC3;
                *w++ = (uint8_t)(*r++ - 0x40);
            }
        }
        *w = '\0';
    }

    void _intensity() {
        if (!_srv.hasArg("plain")){ _srv.send(400,"text/plain",""); return; }
        JsonDocument doc; deserializeJson(doc, _srv.arg("plain"));
        uint8_t v = (uint8_t)(doc["value"] | 4);
        gCfg.intensity = v;
        onIntensityChange(v);
        Storage::saveConfig(gCfg);
        _cors(); _srv.send(200,"application/json","{\"ok\":true}");
    }

    void _resetWifi() {
        _cors(); _srv.send(200,"application/json","{\"ok\":true}");
        delay(300); doWifiReset();
    }

    void _factory() {
        Storage::resetConfig();
        _cors(); _srv.send(200,"application/json","{\"ok\":true}");
        delay(300); doWifiReset();
    }
};
